version: '3.8'

services:
  db_anelie_mysql:
    image: mysql:8.0
    container_name: mysql_anelie
    restart: always
    environment:
      MYSQL_DATABASE: db_anelie
      MYSQL_ROOT_PASSWORD: 12052026
    ports:
      - "3306:3306"
    volumes:
      - mysql_anelie_data:/var/lib/mysql

volumes:
  mysql_anelie_data: